### ISSUE TITLE
v6.13.0 - IOS builds falied to be pushed to TestFlight - App Store Validation Issues

### ISSUE THREAD

**Issue by almahealth** [mieszko4/react-native-zoom-us#224]
`[31mERROR ITMS-90542: "Invalid CFBundleSupportedPlatforms value. The CFBundleSupportedPlatforms key in the Info.plist file in “Payload/Our App Dev.app/MobileRTCResources.bundle/zdcRes.bundle” bundle contains an invalid value, [iPhoneSimulator]. Consider removing the CFBundleSupportedPlatforms key from the Info.plist file. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.`

Zoom devforum thread: [https://devforum.zoom.us/t/v5-10-6-3611-causing-app-store-validation-issues/69823]

**Comment by split** [comment]
[Added issue for adding pod for v5.11.3](https://github.com/zoom-us-community/zoom-sdk-pods/issues/12), that based on the forum thread should resolve the issue.

**Comment by AhmedHalbas** [comment]
The temporary solution is to remove the zdcRes.bundle file in the MobileRTCRecources.bundle (in Pods -> ZoomSDK Folder)

**Comment by mieszko4** [comment]
Please try with new `v6.14.0` and feel free to reopen.
Thnx @zvs001 :rocket:

**Comment by smikheiev** [comment]
@mieszko4 the issue still exists, as the new pod is referencing the old version of the SDK: https://github.com/zoom-us-community/zoom-sdk-pods/blob/master/ZoomSDK.podspec#L13

**Comment by selvakumar-aspire** [comment]
Still facing this issue with v6.14.0.
